export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
}

export const categoriesConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE'
}

export const productsConstants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE'
}

export const productDetail = {
    GET_PRODUCT_DETAIL_REQUEST: 'GET_PRODUCT_DETAIL_REQUEST',
    GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
    GET_PRODUCT_DETAIL_FAILURE: 'GET_PRODUCT_DETAIL_FAILURE',
}

export const purchaseProductConstants = {
    PURCHASE_PRODUCT_REQUEST: 'PURCHASE_PRODUCT_REQUEST',
    PURCHASE_PRODUCT_SUCCESS: 'PURCHASE_PRODUCT_SUCCESS',
    PURCHASE_PRODUCT_FAILURE: 'PURCHASE_PRODUCT_FAILURE',
}

export const brandsConstants = {
    GET_ALL_BRANDS_REQUEST: 'GET_ALL_BRANDS_REQUEST',
    GET_ALL_BRANDS_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
    GET_ALL_BRANDS_FAILURE: 'GET_ALL_BRANDS_FAILURE'
}

export const colorsConstants = {
    GET_ALL_COLORS_REQUEST: 'GET_ALL_COLORS_REQUEST',
    GET_ALL_COLORS_SUCCESS: 'GET_ALL_COLORS_SUCCESS',
    GET_ALL_COLORS_FAILURE: 'GET_ALL_COLORS_FAILURE'
}

export const statusConstants = {
    GET_ALL_STATUS_REQUEST: 'GET_ALL_STATUS_REQUEST',
    GET_ALL_STATUS_SUCCESS: 'GET_ALL_STATUS_SUCCESS',
    GET_ALL_STATUS_FAILURE: 'GET_ALL_STATUS_FAILURE'
}